import 'city.dart'; // Import the City class

class Recipe {
  String label;
  String imageUrl;
  int servings;
  List<Ingredient> ingredients;
  City city; // Add the city property

  Recipe(this.label, this.imageUrl, this.servings, this.ingredients, this.city);

  // Sample recipe list
  static List<Recipe> samples = [
    Recipe(
      'Rujak Cingur',
      'assets/rujak.jpg',
      4,
      [
        Ingredient(0.25, 'ikat', 'kangkung, siangi'),
        Ingredient(100, 'gr', 'taoge'),
        Ingredient(4, 'buah', 'timun, iris tipis'),
        Ingredient(250, 'gr', 'cingur sapi'),
        Ingredient(1, 'buah', 'tahu, goreng lalu potong-potong'),
        Ingredient(0.5, 'papan', 'tempe, potong lalu goreng'),
        Ingredient(2, 'buah', 'lontong ukuran kecil, potong-potong'),
      ],
      City('Surabaya', 'assets/surabaya.jpg'),
    ),
    Recipe(
      'Pecel Semanggi',
      'assets/pecel.jpg',
      2,
      [
        Ingredient(3, 'daun', 'semanggi'),
        Ingredient(2, 'genggam', 'taoge'),
        Ingredient(30, 'gr', 'gula merah'),
        Ingredient(4, 'siung', 'bawang merah'),
        Ingredient(2, 'siung', 'bawang putih'),
        Ingredient(1, 'ruas', 'kencur'),
        Ingredient(3, 'buah', 'cabe rawit'),
      ],
      City('Surabaya', 'assets/surabaya.jpg'),
    ),
    Recipe(
      'Sate klopo',
      'assets/sate.jpg',
      3,
      [
        Ingredient(300, 'gr', 'daging sapi'),
        Ingredient(0.5, 'butir', 'kelapa muda'),
        Ingredient(17, 'buah', 'tusukan sate'),
        Ingredient(4, 'siung', 'bawang merah'),
        Ingredient(3, 'siung', 'bawang putih'),
        Ingredient(3, 'sdm', 'ketumbar'),
        Ingredient(1, 'ruas jari', 'kunyit bakar'),
        Ingredient(1, 'jumput', 'garam (secukupnya)'),
        Ingredient(3, 'jumput', 'gula pasir (secukupnya)'),
      ],
      City('Surabaya', 'assets/surabaya.jpg'),
    ),
    Recipe(
      'Rawon',
      'assets/rawon.jpg',
      5,
      [
        Ingredient(500, 'gr', 'daging sapi'),
        Ingredient(100, 'gr', 'toge kedele'),
        Ingredient(2, 'batang', 'daun bawang'),
        Ingredient(10, 'siung', 'bawang merah'),
        Ingredient(4, 'siung', 'bawang putih'),
        Ingredient(2, 'sdt', 'ketumbar bubuk'),
        Ingredient(5, 'butir', 'kemiri'),
        Ingredient(8, 'buah', 'keluwek'),
        Ingredient(3, 'lembar', 'daun jeruk'),
      ],
      City('Surabaya', 'assets/surabaya.jpg'),
    ),
    Recipe(
      'Lontong balap',
      'assets/lontong.jpg',
      6,
      [
        Ingredient(750, 'gr', 'tauge/kecambah'),
        Ingredient(1.5, 'liter', 'air masak'),
        Ingredient(2, 'tangkai', 'daun seledri'),
        Ingredient(9, 'siung', 'bawang merah'),
        Ingredient(5, 'siung', 'bawang putih'),
        Ingredient(6, 'buah', 'lontong'),
        Ingredient(8, 'buah', 'tahu goreng'),
        Ingredient(1.5, 'sdm', 'tahu petis'),
        Ingredient(6, 'buah', 'lentho'),
      ],
      City('Surabaya', 'assets/surabaya.jpg'),
    ),
    Recipe(
      'Nasi tempong',
      'assets/tempong.jpg',
      4,
      [
        Ingredient(4, 'porsi', 'nasi putih'),
        Ingredient(2, 'siung', 'bawang merah'),
        Ingredient(20, 'buah', 'cabe rawit'),
        Ingredient(3, 'buah', 'cabe besar merah'),
        Ingredient(3, 'buah', 'tomat'),
        Ingredient(4, 'ekor', 'ikan asin'),
        Ingredient(4, 'buah', 'tahu goreng'),
        Ingredient(3, 'lembar', 'kubis'),
      ],
      City('Banyuwangi', 'assets/banyuwangi.jpg'),
    ),
    Recipe(
      'Sego kalak',
      'assets/kalak.jpg',
      3,
      [
        Ingredient(4, 'porsi', 'nasi putih'),
        Ingredient(2, 'ekor', 'ikan pindang salem'),
        Ingredient(3, 'batang', 'daun bawang'),
        Ingredient(1, 'ikat', 'daun kemangi'),
        Ingredient(8, 'buah', 'cabai merah besar'),
        Ingredient(4, 'buah', 'cabe rawit merah'),
        Ingredient(4, 'buah', 'jeruk limau'),
      ],
      City('Banyuwangi', 'assets/banyuwangi.jpg'),
    ),
    Recipe(
      'Rujak soto',
      'assets/rjksoto.jpg',
      1,
      [
        Ingredient(3, 'jenis', 'sayuran yang telah direbus'),
        Ingredient(1, 'sdm', 'kacang tanah goreng'),
        Ingredient(2, 'buah', 'cabe kecil'),
        Ingredient(1, 'sdt', 'petis udang'),
        Ingredient(1, 'lembar', 'daun jeruk'),
        Ingredient(1, 'buah', 'lontong'),
        Ingredient(0.5, 'bungkus', 'bumbu soto instan'),
        Ingredient(650, 'ml', 'air'),
      ],
      City('Banyuwangi', 'assets/banyuwangi.jpg'),
    ),
    Recipe(
      'Ayam kesrut',
      'assets/kesrut.jpg',
      4,
      [
        Ingredient(5, 'buah', 'belimbing wuluh'),
        Ingredient(2, 'siung', 'bawang merah'),
        Ingredient(8, 'buah', 'cabe rawit'),
        Ingredient(5, 'buah', 'cabe besar merah'),
        Ingredient(1, 'buah', 'tomat'),
        Ingredient(2, 'siung', 'bawang putih'),
        Ingredient(4, 'siung', 'bawang merah'),
        Ingredient(750, 'ml', 'air'),
        Ingredient(0.5, 'sdt', 'terasi'),
      ],
      City('Banyuwangi', 'assets/banyuwangi.jpg'),
    ),
    Recipe(
      'Bagiak',
      'assets/bagiak.jpg',
      44,
      [
        Ingredient(500, 'gr', 'gula pasir'),
        Ingredient(200, 'cc', 'air/santan'),
        Ingredient(2, 'butir', 'telur'),
        Ingredient(200, 'gr', 'mentega'),
        Ingredient(1, 'buah', 'tomat'),
        Ingredient(1, 'kg', 'tepung kanji'),
        Ingredient(0.5, 'kg', 'tepung larut'),
        Ingredient(0.5, 'sdt', 'baking soda'),
        Ingredient(0.5, 'sdm', 'garam'),
        Ingredient(0.75, 'sdt', 'bubuk vanili'),
        Ingredient(1, 'sdt', 'bubuk kayu manis/jahe, essence pandan'),
      ],
      City('Banyuwangi', 'assets/banyuwangi.jpg'),
    ),
    Recipe(
      'Sate ayam madura',
      'assets/satemdr.jpeg',
      5,
      [
        Ingredient(300, 'gr', 'dada ayam fillet'),
        Ingredient(150, 'gr', 'kacang tanah'),
        Ingredient(2, 'siung', 'bawang merah'),
        Ingredient(5, 'siung', 'bawang putih'),
        Ingredient(3, 'lembar', 'daun jeruk'),
        Ingredient(1, 'sdm', 'kecap manis'),
        Ingredient(0.5, 'sdt', 'garam'),
        Ingredient(0.75, 'sdt', 'lada bubuk'),
      ],
      City('Madura', 'assets/madura.jpg'),
    ),
    Recipe(
      'Nasi serpang',
      'assets/serpang.jpg',
      3,
      [
        Ingredient(3, 'porsi', 'nasi putih'),
        Ingredient(50, 'gr', 'tahu putih/goreng'),
        Ingredient(5, 'siung', 'bawang merah'),
        Ingredient(2, 'siung', 'bawang putih'),
        Ingredient(3, 'butir', 'kemiri sangrai'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(0.5, 'sdt', 'terasi bakar'),
        Ingredient(1, 'ruas jari', 'lengkuas'),
        Ingredient(65, 'ml', 'santan dan air'),
      ],
      City('Madura', 'assets/madura.jpg'),
    ),
    Recipe(
      'Lorjuk madura',
      'assets/lorjuk.jpg',
      6,
      [
        Ingredient(250, 'gr', 'lorjuk/kerang bambu'),
        Ingredient(4, 'buah', 'cabai merah besar'),
        Ingredient(7, 'siung', 'bawang merah'),
        Ingredient(3, 'siung', 'bawang putih'),
        Ingredient(6, 'buah', 'lontong'),
        Ingredient(1, 'ons', 'kecambah pendek'),
        Ingredient(2, 'buah', 'jeruk nipis'),
        Ingredient(1, 'liter', 'air putih'),
        Ingredient(1, 'ruas', 'jahe'),
      ],
      City('Madura', 'assets/madura.jpg'),
    ),
    Recipe(
      'Topak ladeh',
      'assets/topak.jpg',
      8,
      [
        Ingredient(0.5, 'kg', 'daging sapi'),
        Ingredient(1, 'buah', 'kelapa parut'),
        Ingredient(0.75, 'butir', 'telur ayam'),
        Ingredient(0.5, 'buah', 'manisa'),
        Ingredient(7, 'siung', 'bawang merah'),
        Ingredient(0.5, 'ruas jari', 'kunyit'),
        Ingredient(2, 'butir', 'kencur'),
        Ingredient(2, 'sdm', 'ketumbar bubuk'),
        Ingredient(3, 'lembar', 'dau jeruk'),
      ],
      City('Madura', 'assets/madura.jpg'),
    ),
    Recipe(
      'Nasi glepungan',
      'assets/glepungan.jpg',
      4,
      [
        Ingredient(150, 'gr', 'empok/glepung jagung'),
        Ingredient(0.75, 'butir', 'telur ayam'),
        Ingredient(4, 'ekor', 'ikan asin'),
        Ingredient(4, 'buah', 'tahu dan tempe'),
      ],
      City('Probolinggo', 'assets/probolinggo.jpg'),
    ),
    Recipe(
      'Ketan kratok',
      'assets/ketan.jpg',
      4,
      [
        Ingredient(750, 'gr', 'ketan'),
        Ingredient(750, 'ml', 'santan kental'),
        Ingredient(0.5, 'sdt', 'garam'),
        Ingredient(1, 'buah', 'kelapa setengah tua'),
        Ingredient(200, 'gr', 'gula merah'),
        Ingredient(2, 'lembar', 'daun pandan'),
        Ingredient(50, 'ml', 'air'),
      ],
      City('Probolinggo', 'assets/probolinggo.jpg'),
    ),
    Recipe(
      'Soto kraksaan',
      'assets/kraksaan.jpg',
      2,
      [
        Ingredient(0.75, 'kg', 'daging ayam dan tulang'),
        Ingredient(1, 'butir', 'telur rebus'),
        Ingredient(4, 'siung', 'bawang merah'),
        Ingredient(2, 'siung', 'bawang putih'),
        Ingredient(1, 'ruas', 'jahe'),
        Ingredient(1, 'ruas', 'kunyit'),
        Ingredient(1, 'ruas', 'lengkuas'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(3, 'lembar', 'daun kunyit'),
      ],
      City('Probolinggo', 'assets/probolinggo.jpg'),
    ),
    Recipe(
      'Kepiting olok',
      'assets/kepiting.jpg',
      2,
      [
        Ingredient(0.5, 'kg', 'kepiting olok'),
        Ingredient(0.5, 'sdt', 'merica bubuk'),
        Ingredient(6, 'siung', 'bawang merah'),
        Ingredient(4, 'siung', 'bawang putih'),
        Ingredient(1, 'sdt', 'garam'),
        Ingredient(3, 'sdm', 'minyak goreng untuk tumis'),
        Ingredient(2, 'sdm', 'saos tomat'),
      ],
      City('Probolinggo', 'assets/probolinggo.jpg'),
    ),
  ];
}

class Ingredient {
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}
